dataset:
  name: applications
  table: analytics.fct_applications
  time_column: created_at
  default_grain: day

models:
  - name: applications
    primary_table: analytics.fct_applications
    primary_key: application_id
    time_column: created_at
    dimensions:
      application_id: { column: application_id, type: string }
      channel: { column: channel, type: string }
      state: { column: state, type: string }
    measures:
      is_approved: { column: is_approved, type: int }

metrics:
  - name: applications
    semantic_key: underwriting.applications
    model: applications
    type: count
    expr: dimensions.application_id
    description: Total number of applications
    owner: underwriting

  - name: approvals
    semantic_key: underwriting.approvals
    model: applications
    type: sum
    expr: measures.is_approved
    description: Approved applications (0/1)
    owner: underwriting

  - name: approval_rate
    semantic_key: underwriting.approval_rate
    type: ratio
    numerator: approvals
    denominator: applications
    format: percent
    description: Approval rate
    owner: underwriting
    aliases: [apr_rate]

behaviors:
  global_filters: [date_range, channel, state]
  compare_period:
    enabled: true
    modes: [previous_period]
  drilldown:
    enabled: true
    max_rows: 5000
  export_formats: [csv]

dashboard:
  title: Underwriting Overview
  pages:
    - name: Executive
      include_metrics: [applications, approval_rate]
      views: [kpi, trend, breakdown]
      breakdown_dims: [channel, state]
